name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: install, build, test
        run: |
          npm ci --no-optional --no-audit --progress=false
          npm run lint
          npm run test
          npm run test:rules
          npm run build:docs
          npm pack --loglevel notice 2>&1 >/dev/null | sed -e 's/^npm notice //' && rm *.tgz
